name: Hospital System Production CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: hospital-system
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: 12345678
        ports:
          - 5432:5432

