name: Hospital System Production CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['17']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: hospital-system
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: 12345678
        ports:
          - 5432:5432

    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: java -cp java HelloWorldApp

      - name: Maven compile
        run: mvn clean compile

      - name: Maven run Spring Boot
        run: mvn spring-boot:run

      - name: Test Collection
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
      with:
        collection: collection.json
