name: Hospital System Production CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      JAVA_PROFILES_ATIVE: dev

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Docker-Compouse
        run: docker-compose up

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: collection.json
          reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}

      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME_PROD}}
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}